# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/00_card.ipynb 2
from fastcore.utils import *

# %% ../nbs/00_card.ipynb 4
suits = ["♣️", "♦️", "❤️", "♠️"]
ranks = [None, "A"] + [str(x) for x in range(2,11)] + ["J", "Q", "K"]

# %% ../nbs/00_card.ipynb 12
class Card:
    "A playing card"
    def __init__(self,
                 rank:int, # An index into `ranks`
                 suit:int): # An index into `suits`
        self.suit,self.rank = suit, rank
    def __str__(self): return f"{ranks[self.rank]}{suits[self.suit]}"
    __repr__ = __str__

# %% ../nbs/00_card.ipynb 17
@patch
def __eq__(self:Card, a:Card): return (self.rank,self.suit)==(a.rank, a.suit)
@patch
def __lt__(self:Card, a:Card): return (self.rank,self.suit)<(a.rank, a.suit)
@patch
def __gt__(self:Card, a:Card): return (self.rank,self.suit)>(a.rank, a.suit)
