# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_deck.ipynb.

# %% auto 0
__all__ = ['Deck', 'draw_n']

# %% ../nbs/01_deck.ipynb 2
from .card import *
from fastcore.utils import *
import random

# %% ../nbs/01_deck.ipynb 4
class Deck:
    "A deck of 52 cards not including jokers"
    def __init__(self): self.cards = [Card(r, s) for r in range(1,14) for s in range(4)]
    def __len__(self): return len(self.cards)
    def __repr__(self): return '; '.join(map(str, self.cards))
    def __contains__(self, card): return card in self.cards
    
    def shuffle(self):
        "Shuffles the cards in the deck"
        random.shuffle(self.cards)

# %% ../nbs/01_deck.ipynb 13
@patch
def pop(self:Deck,
        idx:int=-1): # The index of the card to remove, defaulting to the last one.
    "Remove one card from the deck"
    return self.cards.pop()

# %% ../nbs/01_deck.ipynb 17
@patch
def remove(self:Deck,
           card:Card): # Card to remove
    "Removes `card` from the deck or raises exception if it is not there"
    self.cards.remove(card)

# %% ../nbs/01_deck.ipynb 20
def draw_n(n:int, # number of cards to draw
          replace:bool=True): # whether or not to draw with replacement
    "Draw `n` cards, with replacement if `replace`"
    d = Deck()
    d.shuffle()
    if replace: return [d.cards[random.choice(range(len(d.cards)))] for _ in range(n)]
    else: return d.cards[:n]
